### ISSUE TITLE
Model code implementation issues

### ISSUE THREAD

**Issue by Baekstar** [thislzm/UME-Net#2]
Hello author, I am very interested in the model you propose and first of all I would like to thank the author for making the code public. BTW, I am using the Laplace Pyramid in the code to extract the HF and fusing it with BaseModel to generate an image similar to this, may I ask what is wrong?  HF(p1). output(p2)
![image](https://github.com/thislzm/UME-Net/assets/127196083/ea05c2bc-548c-445a-a2aa-1a0f39b23617)
![image](https://github.com/thislzm/UME-Net/assets/127196083/f5625bf4-cad6-44d8-8ad6-0631463d5b7c)

**Comment by thislzm** [comment]
Thank you for your question.  In UME-Net, the fusion of high-frequency information is not a simple addition process.  We encode the high-frequency image obtained from high-frequency decomposition to acquire its high-frequency feature representation.  The AFB module  is then used to adaptively fuse this high-frequency representation with the features from the corresponding RGB image encoding layer.  Additionally, we do not feed the enhanced features of the fused high-frequency components back into the encoding layer to avoid affecting the network’s feature extraction.  Instead, these enhanced high-frequency features serve as guiding information to help the network reconstruct a more realistic dehazed image with detailed preservation.
